services:
  - type: web
    name: jdmatching
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://jdmatching-1.onrender.com
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: jdmatching-1
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://jdmatching.onrender.com/api
    autoDeploy: true
